// src/component/Blog.test.tsx
import { render, screen } from "@testing-library/react";// On importe les fonctions render et screen de la bibliothèque @testing-library/react pour rendre les composants React dans un environnement de test et interagir avec eux. render est utilisé pour monter le composant que nous voulons tester, tandis que screen fournit des méthodes pour sélectionner des éléments dans le DOM rendu, comme getByRole, getByText, etc.
import BlogListPage from "@/app/blog/page";
import PostPage from "@/app/blog/[slug]/page";// On importe les composants BlogListPage et PostPage que nous allons tester. BlogListPage est la page qui affiche la liste des articles de blog, tandis que PostPage est la page de détail d'un article spécifique, identifiée par un slug dans l'URL. Ces imports nous permettent d'accéder à ces composants dans nos tests pour vérifier leur comportement et leur rendu.

describe("Navigation Blog", () => { // On définit une suite de tests pour la navigation du blog en utilisant la fonction describe. Cette suite regroupe les tests liés à la navigation entre la liste des articles et les pages de détail des articles. Le nom "Navigation Blog" est une description claire de ce que cette suite de tests couvre, ce qui facilite la compréhension et l'organisation des tests.
  it("devrait afficher le lien vers l'article Jest", () => { // On définit un test individuel avec la fonction it. Ce test vérifie que la page de liste du blog affiche correctement un lien vers l'article "Maîtriser Jest". Le nom du test "devrait afficher le lien vers l'article Jest" décrit précisément ce que le test vérifie, ce qui aide à comprendre l'objectif du test et à identifier rapidement les problèmes si le test échoue.
    render(<BlogListPage />); // On rend le composant BlogListPage dans l'environnement de test. Cela simule le rendu de la page de liste du blog, ce qui nous permet d'interagir avec les éléments de cette page et de vérifier leur présence et leurs attributs.
    
    const link = screen.getByRole("link", { name: /maîtriser jest/i }); // On utilise screen.getByRole pour sélectionner le lien qui correspond à l'article "Maîtriser Jest". La méthode getByRole("link") sélectionne les éléments de type lien (a), et l'option { name: /maîtriser jest/i } permet de filtrer les liens en fonction de leur texte visible, en utilisant une expression régulière insensible à la casse. Cela nous permet de vérifier que le lien vers l'article "Maîtriser Jest" est présent dans le DOM rendu.
    expect(link).toHaveAttribute("href", "/blog/maitriser-jest"); // On utilise expect pour faire une assertion sur le lien sélectionné. La méthode toHaveAttribute("href", "/blog/maitriser-jest") vérifie que le lien a un attribut href avec la valeur "/blog/maitriser-jest". Cela confirme que le lien est correctement configuré pour diriger vers la page de détail de l'article "Maîtriser Jest" lorsque l'utilisateur clique dessus.
  });
});



describe("Page Détail du Blog", () => {  // On définit une suite de tests pour la page de détail du blog. Cette suite regroupe les tests liés à l'affichage du contenu d'un article de blog spécifique, identifié par un slug dans l'URL. Le nom "Page Détail du Blog" décrit clairement le focus de cette suite de tests, ce qui facilite la compréhension et l'organisation des tests liés à la page de détail des articles.
  it("devrait afficher le titre formaté correctement à partir du slug", async () => { // On définit un test individuel avec la fonction it. Ce test vérifie que la page de détail du blog affiche correctement le titre de l'article formaté à partir du slug. Le nom du test "devrait afficher le titre formaté correctement à partir du slug" décrit précisément ce que le test vérifie, ce qui aide à comprendre l'objectif du test et à identifier rapidement les problèmes si le test échoue. Le mot "async" indique que ce test est asynchrone, ce qui est nécessaire pour tester un composant qui utilise des données asynchrones (comme les paramètres de l'URL).
    // 1. On crée un mock des paramètres sous forme de Promesse
    const mockParams = Promise.resolve({ slug: "nextjs-14-pour-les-pros" }); // On crée une promesse qui résout un objet contenant le slug "nextjs-14-pour-les-pros". Ce mock simule les paramètres que la page de détail du blog recevrait dans une situation réelle, où le slug serait extrait de l'URL. En utilisant Promise.resolve, nous créons une promesse qui se résout immédiatement avec les données spécifiées, ce qui nous permet de tester le composant PostPage de manière asynchrone.

    // 2. On attend le rendu du composant (puisque c'est un Server Component async)
    // Note : On l'appelle comme une fonction car c'est un composant asynchrone
    render(await PostPage({ params: mockParams })); // On rend le composant PostPage en attendant que la promesse des paramètres soit résolue. Comme PostPage est un composant asynchrone qui attend les paramètres, nous devons utiliser await pour s'assurer que nous passons les données correctes au composant avant de le rendre. En appelant PostPage comme une fonction et en lui passant les paramètres mockés, nous simulons le rendu de la page de détail du blog avec les données spécifiques du slug, ce qui nous permet de vérifier que le titre est affiché correctement en fonction du slug fourni.

    // 3. On vérifie que le texte formaté est présent
    // Le replace(/-/g, ' ') devrait transformer le slug en "nextjs 14 pour les pros"
    const title = screen.getByText(/nextjs 14 pour les pros/i); // On utilise screen.getByText pour sélectionner l'élément qui contient le texte "nextjs 14 pour les pros". La méthode getByText(/nextjs 14 pour les pros/i) recherche un élément dont le texte correspond à l'expression régulière insensible à la casse, ce qui nous permet de vérifier que le titre de l'article est affiché correctement en remplaçant les tirets du slug par des espaces. Cette assertion confirme que le composant PostPage traite correctement le slug pour afficher un titre lisible et formaté pour l'utilisateur.
    expect(title).toBeInTheDocument(); // On utilise expect pour faire une assertion sur l'élément de titre sélectionné. La méthode toBeInTheDocument() vérifie que cet élément est présent dans le DOM rendu, ce qui confirme que le titre formaté à partir du slug est effectivement affiché sur la page de détail du blog. Si cette assertion échoue, cela indiquerait que le composant PostPage ne traite pas correctement le slug ou ne rend pas le titre comme prévu.
  });
});

it("devrait correspondre au snapshot final", () => {// On définit un test individuel avec la fonction it. Ce test vérifie que le rendu de la page de liste du blog correspond à un snapshot précédemment enregistré. Le nom du test "devrait correspondre au snapshot final" indique que ce test est destiné à vérifier que le rendu actuel du composant n'a pas changé de manière inattendue par rapport à une version précédente, ce qui est utile pour détecter les régressions visuelles ou les modifications non intentionnelles dans le rendu du composant.
  const { asFragment } = render(<BlogListPage />); // On rend le composant BlogListPage et extrait la fonction asFragment du résultat de render. La fonction asFragment permet de capturer une représentation du DOM rendu sous forme de fragment, ce qui est utilisé pour comparer le rendu actuel avec un snapshot enregistré. En utilisant asFragment, nous pouvons générer un snapshot de la structure HTML actuelle du composant et vérifier qu'elle correspond à ce qui a été précédemment enregistré, ce qui aide à maintenir la cohérence visuelle du composant au fil du temps.
  expect(asFragment()).toMatchSnapshot(); // On utilise expect pour faire une assertion sur le fragment capturé du DOM rendu. La méthode toMatchSnapshot() compare ce fragment avec un snapshot précédemment enregistré. Si le rendu actuel correspond au snapshot, le test réussit. Si le rendu a changé de manière significative (par exemple, en raison de modifications dans le code ou les styles), le test échouera, indiquant que le rendu du composant a été modifié par rapport à la version précédente. Cela permet de détecter les régressions visuelles ou les changements non intentionnels dans l'apparence du composant.
});