import { useState, useCallback,} from 'react'; // On importe les hooks useState, useCallback et useEffect de React. useState est utilisé pour gérer l'état local du composant, en l'occurrence l'utilisateur connecté. useCallback est utilisé pour mémoriser les fonctions login et logout afin d'éviter des re-créations inutiles à chaque rendu. useEffect pourrait être utilisé pour synchroniser l'état avec le localStorage ou pour effectuer des actions secondaires lorsque l'état change, bien que dans ce code spécifique, il n'est pas utilisé.

export const useAuth = () => { // On définit un hook personnalisé appelé useAuth. Ce hook encapsule la logique d'authentification de l'utilisateur, y compris la gestion de l'état de l'utilisateur connecté, les fonctions de connexion et de déconnexion, et la persistance de l'état dans le localStorage. En utilisant ce hook, les composants peuvent facilement accéder à l'état d'authentification et aux fonctions associées sans avoir à dupliquer la logique d'authentification dans chaque composant.
  const [user, setUser] = useState<string | null>(() => { // On utilise useState pour créer une variable d'état user qui peut être de type string ou null. La valeur initiale de user est déterminée par une fonction de rappel qui récupère l'utilisateur enregistré dans le localStorage. En utilisant une fonction de rappel pour l'initialisation, nous nous assurons que la récupération de l'utilisateur à partir du localStorage ne se produit qu'une seule fois lors du montage initial du composant, ce qui améliore les performances en évitant des accès redondants au localStorage à chaque rendu.
    const savedUser = localStorage.getItem('auth_user'); // On récupère l'utilisateur enregistré dans le localStorage en utilisant localStorage.getItem('auth_user'). Si un utilisateur est trouvé, sa valeur sera une chaîne de caractères, sinon elle sera null. Cette ligne permet de restaurer l'état de l'utilisateur connecté à partir du localStorage lorsque le composant est monté, ce qui permet de maintenir la session de l'utilisateur même après un rafraîchissement de la page.
    return savedUser || null; // On retourne la valeur de savedUser si elle existe, sinon on retourne null. Cela garantit que l'état user est correctement initialisé en fonction de la présence ou de l'absence d'un utilisateur enregistré dans le localStorage. Si aucun utilisateur n'est trouvé, user sera initialisé à null, indiquant qu'aucun utilisateur n'est actuellement connecté.
  });

  const login = useCallback((username: string) => { // On définit une fonction de connexion login qui prend un nom d'utilisateur en paramètre. Cette fonction est mémorisée avec useCallback pour éviter des re-créations inutiles à chaque rendu. Lorsqu'elle est appelée, elle met à jour l'état user avec le nom d'utilisateur fourni et enregistre ce nom d'utilisateur dans le localStorage sous la clé 'auth_user'. Cela permet de maintenir la session de l'utilisateur même après un rafraîchissement de la page, en stockant les informations d'authentification dans le localStorage.
    setUser(username); // On met à jour l'état user avec le nom d'utilisateur fourni. Cela indique que l'utilisateur est maintenant connecté et que son nom d'utilisateur est stocké dans l'état du composant, ce qui peut être utilisé pour afficher des informations personnalisées ou pour conditionner l'affichage de certaines parties de l'interface utilisateur en fonction de l'état de connexion.
    localStorage.setItem('auth_user', username); // On enregistre le nom d'utilisateur dans le localStorage sous la clé 'auth_user'. Cela permet de persister l'état de connexion de l'utilisateur même après un rafraîchissement de la page, en stockant les informations d'authentification dans le localStorage. Lorsque le composant est monté à nouveau, il peut récupérer cette information pour restaurer l'état de l'utilisateur connecté.
  }, []); // Le tableau de dépendances vide [] indique que la fonction login ne dépend d'aucune variable externe, ce qui signifie qu'elle ne sera créée qu'une seule fois lors du montage initial du composant.

  const logout = useCallback(() => { // On définit une fonction de déconnexion logout qui est également mémorisée avec useCallback. Lorsqu'elle est appelée, elle réinitialise l'état user à null, indiquant que l'utilisateur est maintenant déconnecté, et supprime l'entrée 'auth_user' du localStorage pour effacer les informations d'authentification stockées. Cela permet de mettre fin à la session de l'utilisateur et d'empêcher la restauration de l'état de connexion lors du prochain montage du composant.
    setUser(null); // On réinitialise l'état user à null, indiquant que l'utilisateur est maintenant déconnecté. Cela met fin à la session de l'utilisateur dans l'état du composant, ce qui peut être utilisé pour conditionner l'affichage de certaines parties de l'interface utilisateur en fonction de l'état de connexion.
    localStorage.removeItem('auth_user'); // On supprime l'entrée 'auth_user' du localStorage pour effacer les informations d'authentification stockées. Cela empêche la restauration de l'état de connexion lors du prochain montage du composant, assurant que l'utilisateur reste déconnecté même après un rafraîchissement de la page.
  }, []); // Le tableau de dépendances vide [] indique que la fonction logout ne dépend d'aucune variable externe, ce qui signifie qu'elle ne sera créée qu'une seule fois lors du montage initial du composant.

  return { // On retourne un objet contenant l'état de l'utilisateur connecté, une indication de si l'utilisateur est connecté ou non, et les fonctions de connexion et de déconnexion. L'état user contient le nom d'utilisateur si un utilisateur est connecté, ou null s'il n'y a pas d'utilisateur connecté. La propriété isLoggedIn est une valeur booléenne qui indique si un utilisateur est actuellement connecté (true) ou non (false). Les fonctions login et logout permettent aux composants qui utilisent ce hook de gérer l'authentification de l'utilisateur en appelant ces fonctions pour se connecter ou se déconnecter.
    user,
    isLoggedIn: !!user,
    login,
    logout,
  };
};